=== VladSimka/Java_Labs/Lab14/target/classes/bank.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">

<!--    <xs:simpleType name="depositType">-->
<!--        <xs:restriction base="xs:string">-->
<!--            <xs:enumeration value="до востребования"/>-->
<!--            <xs:enumeration value="срочный"/>-->
<!--            <xs:enumeration value="расчетный"/>-->
<!--            <xs:enumeration value="накопительный"/>-->
<!--            <xs:enumeration value="сберегательный"/>-->
<!--            <xs:enumeration value="металлический"/>-->
<!--        </xs:restriction>-->
<!--    </xs:simpleType>-->

    <xs:complexType name="bank">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="country" type="xs:string"/>
            <xs:element name="type" type="xs:string"/>
            <xs:element name="depositor" type="xs:string"/>
            <xs:element name="accountId" type="xs:integer"/>
            <xs:element name="amountOnDeposit" type="xs:double"/>
            <xs:element name="profitability" type="xs:double"/>
            <xs:element name="timeConstraints" type="xs:integer"/>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="banks">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="bank" type="bank" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== VladSimka/Java_Labs/Lab14/src/main/resources/bank.xml
<?xml version="1.0" encoding="UTF-8"?>
<banks xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="bank.xsd">
    <bank>
        <name>Bank A</name>
        <country>Russia</country>
        <type>срочный</type>
        <depositor>Alice</depositor>
        <accountId>2</accountId>
        <amountOnDeposit>10000</amountOnDeposit>
        <profitability>3.5</profitability>
        <timeConstraints>12</timeConstraints>
    </bank>
    <bank>
        <name>Bank B</name>
        <country>USA</country>
        <type>до востребования</type>
        <depositor>Bob</depositor>
        <accountId>1</accountId>
        <amountOnDeposit>5000</amountOnDeposit>
        <profitability>2</profitability>
        <timeConstraints>0</timeConstraints>
    </bank>
    <bank>
        <name>Bank C</name>
        <country>Belarus</country>
        <type>расчетный</type>
        <depositor>Vlad</depositor>
        <accountId>5</accountId>
        <amountOnDeposit>1000</amountOnDeposit>
        <profitability>3</profitability>
        <timeConstraints>0</timeConstraints>
    </bank>
</banks>
